sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '@Ljx021225'

  alioss:
    access-key-secret: SXPGD5SkVBRCTaEltkdarMQCEJWmKg
    bucket-name: test-dem11
    access-key-id: LTAI5tCVmj5Qi7tfGVzsGNQp
    endpoint: oss-ap-southeast-1.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    password: Ljx021225
    database: 0
